// This file is auto-generated by nextjs-studio.
// Do not edit manually — re-run `npx nextjs-studio --generate-types` to update.

// Branded scalar types — structurally strings/numbers but semantically distinct.
declare const __brand: unique symbol;
type Brand<T, B extends string> = T & { readonly [__brand]: B };

export type Email     = Brand<string, 'Email'>;
export type HttpUrl   = Brand<string, 'HttpUrl'>;
export type ISODate   = Brand<string, 'ISODate'>;
export type MediaPath = Brand<string, 'MediaPath'>;
export type ID        = Brand<string, 'ID'>;
export type Slug      = Brand<string, 'Slug'>;

/** Data shape for the "about" collection. */
export interface AboutEntry {
  paragraph1: string;
  paragraph2: string;
  paragraph3: string;
  imageUrl: string;
  imageAlt: string;
}

/** Data shape for the "community" collection. */
export interface CommunityEntry {
  name: string;
  acronym: string;
  city: string;
  description: string;
  link: HttpUrl;
  logoUrl: string;
  order: number;
}

/** Data shape for the "counts" collection. */
export interface CountsEntry {
  participants: string;
  participantsLabel: string;
  talks: string;
  talksLabel: string;
  speakers: string;
  speakersLabel: string;
  days: string;
  daysLabel: string;
}

/** Data shape for the "equipe" collection. */
export interface EquipeEntry {
  name: string;
  role: string;
  photoUrl: string;
  linkedin: string;
  order: number;
}

/** Data shape for the "faq" collection. */
export interface FaqEntry {
  question: string;
  answer: string;
  order: number;
}

/** Data shape for the "ingress" collection. */
export interface IngressEntry {
  name: string;
  price: string;
  description: string;
  icon: string;
  featured: boolean;
  badge: string;
  ctaLabel: string;
  ctaUrl: HttpUrl;
  note: string;
  benefits: Array<{
    item: string;
  }>;
  order: number;
}

/** Data shape for the "patrocinadores" collection. */
export interface PatrocinadoresEntry {
  name: string;
  logoUrl: string;
  link: HttpUrl;
  tier: string;
  order: number;
}

/** Data shape for the "patrocinio-tier" collection. */
export interface PatrocinioTierEntry {
  name: string;
  price: string;
  icon: string;
  featured: boolean;
  badge: string;
  ctaLabel: string;
  benefits: Array<{
    item: string;
  }>;
  order: number;
}

/** Data shape for the "schedule" collection. */
export interface ScheduleEntry {
  title: string;
  time: string;
  speaker: string;
  stage: string;
  tag: string;
  avatar: string;
  slug: string;
  order: number;
}

/** Data shape for the "settingssite" collection. */
export interface SettingssiteEntry {
  showHero: boolean;
  showAbout: boolean;
  showCounts: boolean;
  showIngress: boolean;
  showSchedule: boolean;
  showSpeakers: boolean;
  showSponsors: boolean;
  showSponsorship: boolean;
  showUserGroups: boolean;
  showVenue: boolean;
  showFaq: boolean;
  showCta: boolean;
  venueName: string;
  venueAddress: string;
  venueCity: string;
  venueMapUrl: string;
  instagram: HttpUrl;
  linkedin: HttpUrl;
  twitter: HttpUrl;
  youtube: HttpUrl;
  contactEmail: Email;
  sponsorshipEmail: Email;
  codeOfConductUrl: string;
  privacyPolicyUrl: string;
}

/** Data shape for the "speakers" collection. */
export interface SpeakersEntry {
  name: string;
  role: string;
  company: string;
  photo: string;
  linkedin: string;
  twitter: string;
  github: string;
  slug: string;
  order: number;
}

// Augment both entry points so queryCollection() is fully typed regardless of import path.
declare module 'nextjs-studio' {
  interface CollectionTypeMap {
    "about": AboutEntry;
    "community": CommunityEntry;
    "counts": CountsEntry;
    "equipe": EquipeEntry;
    "faq": FaqEntry;
    "ingress": IngressEntry;
    "patrocinadores": PatrocinadoresEntry;
    "patrocinio-tier": PatrocinioTierEntry;
    "schedule": ScheduleEntry;
    "settingssite": SettingssiteEntry;
    "speakers": SpeakersEntry;
  }
}
declare module 'nextjs-studio/server' {
  interface CollectionTypeMap {
    "about": AboutEntry;
    "community": CommunityEntry;
    "counts": CountsEntry;
    "equipe": EquipeEntry;
    "faq": FaqEntry;
    "ingress": IngressEntry;
    "patrocinadores": PatrocinadoresEntry;
    "patrocinio-tier": PatrocinioTierEntry;
    "schedule": ScheduleEntry;
    "settingssite": SettingssiteEntry;
    "speakers": SpeakersEntry;
  }
}
